language: node_js
os:
 - linux
 - osx
before_install:
 - npm install -g grunt-cli
install:
 - npm install
 - grunt tsd
node_js: 
 - "0.12"
 - "0.10"
 - "0.8"
script: 
 - grunt test
matrix:
 fast_finish: true
 allow_failures:
  - nodejs: "0.8"
