sudo: required
services:
 - docker
env:
 - DOCKER_IMAGE="node:0.10"
 - DOCKER_IMAGE="node:0.12"
 - DOCKER_IMAGE="node:4.0.0"
install:
 - docker pull $DOCKER_IMAGE
script:
 - docker run -v $PWD:/build -t $DOCKER_IMAGE /bin/bash -c "cd /build && npm install -g grunt-cli && npm install && grunt tsd && grunt test"
