os: Windows Server 2012 R2
init:
 - git config --global core.autocrlf input
environment:
 matrix:
  - nodejs_version: "0.8"
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"
matrix:
 allow_failures:
  - nodejs_version: "0.11"
  - nodejs_version: "0.8"
install:
 - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
 - npm install
 - npm install -g grunt-cli
test_script:
 - node --version
 - npm --version
 - grunt test
build: off
version: "{build}"
